version: "3.8"

services:
  database:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=nettasec_global_db
      - POSTGRES_USER=nettasec
      - POSTGRES_PASSWORD=nettaseclocal
    ports:
      - "5437:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "nettaseclocal"]
    volumes:
      - redis:/data

volumes:
  db:
  redis:
